{-# LANGUAGE OverloadedStrings #-}
module Languages
    ( Language (..)
    , languages
    , defaultLanguage
    , otherLanguage
    , languageHome
    , languageCtx
    , translationUrlMaybe
    , canonicalUrlMaybe
    , siteUrl
    ) where

import           Data.List                  (stripPrefix)
import           Data.Maybe                 (fromMaybe)
import           System.FilePath.Posix      (splitFileName)

import           Hakyll


-- | A language the site is available in.
--
-- The default language (French) lives at the root of the site, every other
-- language is served below a prefix (English below @\/en\/@).  Because a
-- language's source files are stored under the very same prefix, the routing
-- of both languages is identical.
data Language = Language
    { langCode          :: String -- ^ ISO 639-1 code, also used as @<html lang>@.
    , langPrefix        :: String -- ^ Source/route prefix, @""@ or @"en\/"@.
    , langLabel         :: String -- ^ Name shown in the language switcher.
    , langDateFormat    :: String -- ^ @strftime@ format of the @date@ field.
    , trHome            :: String -- ^ Title of the home page.
    , trSiteDescription :: String -- ^ Fallback @description@ for @<meta>@.
    , trAllWritings     :: String -- ^ Title of the all-posts page.
    , trRecentArticles  :: String -- ^ Heading of the recent articles list.
    , trArticlesByCat   :: String -- ^ Heading of the per-category article list.
    , trReadMore        :: String -- ^ "Read more" link of a teaser.
    , trProjects        :: String -- ^ Heading of the sidebar projects list.
    , trRssTitle        :: String -- ^ Title of the sidebar RSS link.
    , trBy              :: String -- ^ Author prefix in a signature.
    , trOn              :: String -- ^ Date prefix in a signature.
    , trGeneratedBy     :: String -- ^ Footer credit.
    , trThemeToggle     :: String -- ^ Label of the dark mode toggle button.
    , trFeedTitle       :: String
    , trFeedDescription :: String
    }


french :: Language
french = Language
    { langCode          = "fr"
    , langPrefix        = ""
    , langLabel         = "Français"
    , langDateFormat    = "%d/%m/%Y"
    , trHome            = "Accueil"
    , trSiteDescription = "Blog: retrocomputing, hacks et projets."
    , trAllWritings     = "Tous les écrits"
    , trRecentArticles  = "Articles récents"
    , trArticlesByCat   = "Articles par catégories"
    , trReadMore        = "Lire la suite"
    , trProjects        = "Projets"
    , trRssTitle        = "RSS Flux"
    , trBy              = "par"
    , trOn              = "le"
    , trGeneratedBy     = "Site généré par"
    , trThemeToggle     = "Changer de thème"
    , trFeedTitle       = "NeZetiC.net feed"
    , trFeedDescription = "NeZetiC.net RSS feed"
    }


english :: Language
english = Language
    { langCode          = "en"
    , langPrefix        = "en/"
    , langLabel         = "English"
    , langDateFormat    = "%Y-%m-%d"
    , trHome            = "Home"
    , trSiteDescription = "Blog: retrocomputing, hacks and projects."
    , trAllWritings     = "All posts"
    , trRecentArticles  = "Recent articles"
    , trArticlesByCat   = "Articles by category"
    , trReadMore        = "Read more"
    , trProjects        = "Projects"
    , trRssTitle        = "RSS Feed"
    , trBy              = "by"
    , trOn              = "on"
    , trGeneratedBy     = "Site generated by"
    , trThemeToggle     = "Toggle theme"
    , trFeedTitle       = "NeZetiC.net feed (English)"
    , trFeedDescription = "NeZetiC.net RSS feed (English)"
    }


languages :: [Language]
languages = [french, english]


defaultLanguage :: Language
defaultLanguage = french


-- | The single other language of the site (the site only has two).
otherLanguage :: Language -> Language
otherLanguage current = case others of
    (other : _) -> other
    []          -> error "Languages.otherLanguage: no other language"
  where
    others = [l | l <- languages, langCode l /= langCode current]


-- | URL path of a language's home page.  Derived from 'siteUrl' so it is
-- byte-for-byte the same string the router produces for the home page
-- identifier (which 'homeFlag' relies on when comparing routes).
languageHome :: Language -> String
languageHome lang = siteUrl (langPrefix lang ++ "index.html")


-- | Context exposing the UI strings of a language, plus a link to the
-- translated version of the current page.
languageCtx :: Language -> Context a
languageCtx lang =
       constField "lang" (langCode lang)
    <> constField "site_description" (trSiteDescription lang)
    <> dateField "date" (langDateFormat lang)
    <> dateField "date_iso" "%Y-%m-%d"
    <> constField "all_writings" (trAllWritings lang)
    <> constField "recent_articles" (trRecentArticles lang)
    <> constField "articles_by_category" (trArticlesByCat lang)
    <> constField "read_more" (trReadMore lang)
    <> constField "rss_title" (trRssTitle lang)
    <> constField "by" (trBy lang)
    <> constField "on" (trOn lang)
    <> constField "generated_by" (trGeneratedBy lang)
    <> constField "theme_toggle" (trThemeToggle lang)
    <> constField "home_url" (languageHome lang)
    <> constField "posts_url" (languageHome lang ++ "posts/")
    <> constField "rss_url" (languageHome lang ++ "rss.xml")
    <> constField "atom_url" (languageHome lang ++ "atom.xml")
    <> field "auto_lang" (homeFlag lang)
    <> switchCtx lang


-- | @\"1\"@ on the language's home page and @\"\"@ elsewhere.  The
-- client-side language <em>auto-detection</em> only runs on the home page, so
-- an inbound deep link to the other language is never bounced by it.  (A
-- stored manual preference is separate and may still redirect a deep link
-- once per session.)
--
-- Read the flag via <html data-auto-lang>; an empty value keeps the template
-- simple (no conditional).
-- Recognised by route rather than by file name, so a home page sourced from
-- @index.md@\/@index.markdown@ keeps working: the home page is whatever
-- resolves to the language's home URL.
homeFlag :: Language -> Item a -> Compiler String
homeFlag lang item = do
    mroute <- getRoute (itemIdentifier item)
    return $ if fmap siteUrl mroute == Just (languageHome lang)
                then "1"
                else ""


-- | Fields describing the link towards the same page in the other language.
switchCtx :: Language -> Context a
switchCtx current =
       field "switch_url" (switchUrl current)
    -- Like @switch_url@ but empty when there is no actual translation.  Used
    -- for @data-alt-url@: the redirect must not send a deep link to the
    -- other language's home page when the requested page has no translation.
    <> field "switch_url_optional" (fmap (fromMaybe "") . translationUrlMaybe current other)
    <> constField "switch_lang" (langCode other)
    <> constField "switch_label" (langLabel other)
  where
    other = otherLanguage current


-- | URL of the current page translated in the given target language, or
-- 'Nothing' when that translation does not exist.
--
-- Items outside the language trees (the 404 page, anything rendered through
-- @templates/default.html@ but not below a language prefix) have no
-- translation: unmatched prefixes yield 'Nothing' rather than a guessed
-- identifier, which matters because the result feeds @rel=alternate@.
translationUrlMaybe :: Language -> Language -> Item a -> Compiler (Maybe String)
translationUrlMaybe current target item = do
    let path = toFilePath (itemIdentifier item)
    case stripPrefix (langPrefix current) path of
        Nothing       -> return Nothing
        Just stripped -> do
            let targetId = fromFilePath (langPrefix target ++ stripped)
            mroute <- getRoute targetId
            return (siteUrl <$> mroute)


-- | URL of the current page translated in the given target language.  Falls
-- back to the target language's home page when no translation exists, so that
-- the visible switcher link is always usable.  @rel=alternate@ and the
-- redirect use 'translationUrlMaybe' instead: a fallback there would produce
-- non-reciprocal @hreflang@ clusters or silently drop the requested page.
translationUrl :: Language -> Language -> Item a -> Compiler String
translationUrl current target item = do
    murl <- translationUrlMaybe current target item
    case murl of
        Just url -> return url
        Nothing  -> do
            mhome <- getRoute (fromFilePath (langPrefix target ++ "index.html"))
            return $ maybe (languageHome target) siteUrl mhome


-- | URL of the current page translated in the other language.
switchUrl :: Language -> Item a -> Compiler String
switchUrl current = translationUrl current (otherLanguage current)


-- | URL of a page itself, or 'Nothing' when it has no route.  Used for the
-- self-referential canonical URL; a routeless item advertises nothing rather
-- than pretending to live at the site root.
canonicalUrlMaybe :: Item a -> Compiler (Maybe String)
canonicalUrlMaybe item = do
    mroute <- getRoute (itemIdentifier item)
    return (siteUrl <$> mroute)


-- | Turn a Hakyll route (like @en\/posts\/foo\/index.html@) into an absolute
-- site URL (like @\/en\/posts\/foo\/@).
--
-- The trailing slash is load-bearing: @index.html@ is stripped so the result
-- is a directory URL ending in @\/@.  'languageHome' is defined in terms of
-- this function and "languageCtx" appends feed and section paths to it
-- (@... ++ "posts/"@, @++ "rss.xml"@, @++ "atom.xml"@), so it must keep
-- producing @\/en\/@ (not @\/en@).  Do not "simplify" the trailing slash away.
siteUrl :: String -> String
siteUrl path = case splitFileName path of
    ("./", "index.html") -> "/"
    (dir, "index.html")  -> ensureRoot dir
    _                    -> ensureRoot path
  where
    ensureRoot s = "/" ++ dropWhile (== '/') s
